feat: Added feature for creating a new geofence with a pre-defined square
aws-amplify/maplibre-gl-js-amplify pull request #68
Opened 2021-11-10 00:05 UTC by thaddmt

#### Description of changes
- Added feature for creating a geofence
- Clicking add button shows a prompt for naming the geofence/ setting the id
- Clicking add confirm button adds a predefined square geofence that to the screen which the developer can edit
- Gif below of the features added

![Untitled](https://user-images.githubusercontent.com/68032955/141025253-a237718c-7bd5-4fb4-b897-df849d5d1afc.gif)

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

2021-11-10 00:24 UTC, Milan-Shah approved these changes

2021-11-16 00:14 UTC, TreTuna requested changes
A few little things, mostly things that seem like they can be removed.

2021-11-16 00:14 UTC, TreTuna commented on src/AmplifyGeofenceControl.ts
> +    console.log(this._mapBoxDraw.get(this._editingGeofenceId));
Remove console logs?
```suggestion
```

2021-11-16 00:14 UTC, TreTuna commented on src/AmplifyGeofenceControl.ts
> +    // });
Do we need this anymore?
```suggestion
```

2021-11-16 00:14 UTC, TreTuna commented on src/utils.ts
> +import { lineString, point } from "@turf/helpers";
Looks like the only thing used from these imports is:
```suggestion
import { point } from "@turf/helpers";
```

2021-11-16 00:14 UTC, TreTuna commented on src/utils.ts
> +import { Coordinates, NamedLocation, Geofence, Polygon } from "./types";
I don't see either of these new imports being used in this file.
```suggestion
import { AnySourceImpl, GeoJSONSource } from "maplibre-gl";
import { Coordinates, NamedLocation, Geofence } from "./types";
```

2021-11-16 18:51 UTC, merged